<?php

// 日志解析类型

$Global_Log_Resolve=array(
		'stall' => array(
				'op_type' =>array(
					'Buy' => '购买物品',
					'BuyPet' => '购买宠物',
					'BuyCoin' => '购买银两',
					),
				'result_type'=>array(
					'Succ' => '交易成功',
					'Discard_Pet_Fail' => '取出宠物失败',
				),
		),
		'gold_shop' => array(
				'op_type' => array(
					'BuyShopItem' => '购买物品',
					),
				'result_type' => array(
					'Succ' => '交易成功',
					),
				'price_type' => array(
					'0' => '绑定元宝',
					'2' => '元宝',
					),
		),
		'money_gold' => array(
				'op_type' => array(
					'UseGold' => '使用非绑元宝',
					'UseGoldBind' => '使用绑定元宝',
					'UseAllGold' => '使用所有元宝',
					'Add' => '添加所有元宝',
					'AddGold' => '添加非绑元宝',
					'AddGoldBind' => '添加绑定元宝',
					),
				'op_result' => array(
					'Succ' => '成功',
					),
				'use_for' => array(
					'EquipStrenClearTimer' => '装备强化清除冷却时间元宝消耗',
					'OriginClearTimer' => '人物天赋升级清除冷却时间元宝消耗',
					'MartixOriginClearTimer' => '阵法天赋升级升级清除冷却时间元宝消耗',
					'MentalityClearTimer' => '元神升级清除冷却时间元宝消耗',
					'ShopUse' => '商城购买道具消耗',
					'GuildCreate' => '宗族创建元宝消耗',
					'GuildContribute' => '宗族捐献元宝消耗',
					'RealiveNow' => '角色复活',
					'RealiveHereNow' => '角色原地复活',
					'EquipStrenCertainSucc' => 'VIP装备强化必定成功',
					'TianshuTaskRefresh' => '天书任务元宝刷新',
					'VipTianshuStarRefresh' => 'VIP天书任务直接刷5星',
					'VipEscortRefresh' => 'VIP运镖直接刷橙色',
					'EscortRefresh' => '运镖元宝刷新',
					'EscortRob' => '元宝劫镖',
					'DongtianTrainCost' => '修炼花费元宝',
					'DongtianAddTrainGrid' => '修炼增加格子',
					'TrainBreak' => '修炼突破',
					'ClearBreakCD' => '清除突破CD',
					'ClearMentalityCD' => '清除元神CD',
					'ClearOriginCD' => '清除天赋CD',
					'DunwuCost' => '顿悟花费元宝',
					'AddXianfaStorage' => '仙法增加格子',
					'OfficerFoster' => '武将洗髓',
					'EscortAccelerate' => '运镖加速',
					'KnapsackStorageExtendGridNum' => '背包仓库扩展格子',
					'ClearMartixOriginCD' => '清除阵法天赋CD',
					'QieshiCost' => '元宝切石',
					'ClearQieshiCD' => '清除切石CD',
					'EncourageUse' => '世界BOSS鼓舞',
					'ArenaRefreshOpponent' => '竞技场敌人刷新',
					'ArenaChallenge' => '竞技场额外挑战',
					'CleanupAccelerate' => '挂机加速',
					'TreasureChestCost' => '元宝斩仙',
					'TaskReward'=>'任务奖励',
					'DefinedGift'=>'固定礼包开出',
					'RandGift'=>'随机礼包开出',
					'GetAccountGold' => '充值',
					'CreateGuildFailReturn' => '元宝创建宗族失败返还',
					'CampPositionSalary' => '阵营官职俸禄',
					'MailReceive' => '邮件附件提取',
					'AchiveReward' => '成就奖励',
					'QieshiReward' => '切石获得礼金',
					'EquipFlushLock'=>'装备洗练锁',
					'MysteriousShop'=>'神秘商店',
					'RefrashBoardTask'=>'刷新悬赏任务',
					'GuildOpenBook'=>'宗族密经召唤',
					'VipBuyEnergyToken'=>'vip购买通神令',
					'PersonMapFlushPoint'=>'个人副本刷新',
					'LianTi'=>'炼体',
					'ChestShopBuy'=>'龙脉宝箱',
					'ForbitAreaFlushTower'=>'镇妖塔刷新',
					'BoardTaskBuyBuff'=>'悬赏固定橙色任务',
					'XRoleArenaCleanAttackCD'=>'竞技场清除挑战CD',
					'MonsterCityReliveNow'=>'怪物攻城原地复活',
					'OfficerChuancheng'=>'家将传承',
					'LiehunConsume'=>'猎魂',
					'LiehunWagerBiSheng'=>'猎魂必胜',
					),
		),
		'money_coin' => array(
				'op_type' => array(
					'UseCoin' => '使用银两',
					'UseCoinTwo' => '使用两种',
					'UseAllCoin' => '使用所有银两',
					'UseAll' => '使用所有',
					'Add' => '添加所有银两',
					'AddCoin' => '添加非绑银两',
					'AddCoinBind' => '添加绑定银两',
					),
				'op_result' => array(
					'Succ' => '成功',
					),
				'coin_add'=>array(
				        'ResFightReward'=>'银矿战',
				        'EscortFinish'=>'护送神兵',
				        'TaskReward'=>'悬赏任务',
				        'QieshiReward'=>'招财进宝',
				        'XArenaAttackReward'=>'竞技场奖励',
				        'CoinRuneUse'=>'使用银两符',
				        'WorldBossReward'=>'世界BOSS',
				        'QunXianWarCombat'=>'群仙战',
				        'MonsterCityReward'=>'妖兽来袭',
				        'other'=>'其它',
				),
				'coin_use'=>array(
				        'EquipStrengthen'=>'装备强化',
				        'WudaoCost'=>'悟道费用',
				        'LiehunConsume'=>'猎魂',
				        'GuildContribute'=>'宗族捐献',
				        'other'=>'其它',
				),
				'coin_use_type'=>array(
				        'EquipStrengthen'=>'强化统计',
				        'WudaoCost'=>'悟道统计',
				        'LiehunConsume'=>'家将猎魂',
				        'GuildContribute'=>'宗族捐献',
				),
				'use_for' => array(
					'MentalityUpgrade' => '升级元神消耗',
					'NpcShopUse' => 'NPC商店购买物品',
					'DongtianTrainCost' => '洞天福地银两修炼消耗',
					'DongtianAddTrainGrid' => '洞天福地增加修炼位元宝消耗',
					'GuildCreate' => '宗族创建消耗',
					'PublicSaleBuy' => '买拍卖品消耗',
					'Other' => '其他（GM命令）',
					'TradeIn' => '交易获得',
					'WorldBossReward' => '世界BOSS胜利获得金钱',
					'EquipUnstrengthen' => '装备降级',
					'CoinRuneUse' => '银两符使用',
					'NpcShopSell' => 'npc商店卖',
					'MailReceive' => '邮件附件获得',
					'NpcShop' => '商店买',
					'TradeOut' => '交易',
					'PK_Cost' => 'PK消费',
					'GuildContribute' => '宗族贡献',
					'EquipDecompose' => '装备分解',
					'EquipDressFusion' => '时装融合',
					'EquipExtendHole' => '装备打孔',
					'EquipFlush' => '装备洗练',
					'EquipInlay' => '装备宝石镶嵌',
					'EquipLiftLevel' => '装备提阶',
					'EquipMountEvolve' => '坐骑进阶',
					'EquipMountFlush' => '坐骑洗髓',
					'EquipRefine' => '装备精炼',
					'EquipRepair' => '装备修理',
					'EquipStrengthen' => '装备强化',
					'EquipTransfer' => '装备转移',
					'EquipUnInlay' => '装备宝石摘除',
					'EquipUpgrade' => '装备升级',
					'DongtianTrainCost' => '修炼费用',
					'WudaoCost' => '悟道费用',
					'SkillUpgrade' => '技能升级费用',
					'MailSend' => '发送邮件固定邮资',
					'PublicSaleChargeCost' => '拍卖管理费',
					'OfficerInnEmploy' => '武将招募费用',
					'GemstoneCompose' => '宝石合成',
					'ItemCompose' => '一般物品合成',
					'PotCompose' => '熔炉合成',
					'TaskReward'=>'任务奖励',
					'DefinedGift'=>'固定礼包开出',
					'RandGift'=>'随机礼包开出',
					'NpcShopSell' => '商店卖',
					'CreateGuildFailReturn' => '创建宗族失败返还银两',
					'CampPositionSalary' => '阵营官职俸禄',
					'MailReceive' => '邮件附件提取',
					'EscortFinish' => '运镖成功',
					'TradeIn' => '交易获得',
					'MailReceive' => '邮件附件提取',
					'EscortFinish' => '运镖成功',
					'TradeIn' => '交易获得',
					'CoinRuneUse' => '使用银两符',
					'RandomBossReward' => '云游BOSS奖励',
					'WorldBossReward' => '世界BOSS奖励',
					'EquipUnstrengthen' => '装备降级',
					'EscortRobReward' => '劫镖奖励',
					'EscortProtectFinish' => '护镖结束奖励',
					'PK_Reward' => 'PK奖励',
					'SellXianfa' => '卖仙法',
					'SellAllXianfa' => '一键卖所有仙法',
					'PushMapReward' => '推图奖励',
					'QieshiReward' => '切石获得银两',
					'HuanJingReward' => '幻境通关奖励',
					'PushMapReward' => '推图奖励',
					'QieshiReward' => '切石获得银两',
					'HuanJingReward' => '幻境通关奖励',
					'ArenaRankReward' => '竞技场积分奖励',
					'ExchangeWeiwang' => '阵营威望换取银两',
					'LiehunConsume'=>'猎魂',
					),
		),
		'country' =>array(
			'0'	=>	'新手',
			'1'	=>	'昆仑',
			'2' => 	'蓬莱',
			'3'	=>	'蜀山',
		),
		'professional' =>array(
			'0' => 	'新手',
			'1' => 	'剑灵',
			'2'	=>	'刺客',
			'3' => 	'笔仙',
			'4' => 	'法尊',
			'11' => '剑圣',
			'12' => '隐刺',
			'13' =>	'笔神',
			'14' => '法皇',
		),
		'sex' => array(
			'0'=>'女',
			'1'=>'男',
		),
		'sex1'=>array(
			'0'=>'f',
			'1'=>'m',
		),
		'quality' => array(
			'0'=>'普通',
			'1'=>'优秀',
			'2'=>'精良',
			'3'=>'卓越',
			'4'=>'完美',
			'5'=>'仙器',
			'6'=>'传说',
		),
		'roleskill_type' =>array(	//技能
			//太玄
			'1001' => '青冥幻斩',
			'1002' => '剑气纵横',
			'1004' => '寒冰剑气',
			'1008' => '一气化三清',
			//瑶池
			'2001' => '狂斩',
			'2002' => '月影千华',
			'2011' => '破灭轮回',
			'2009' => '天外飞仙诀',
			//离火
			'3001' => '冰霜箭',
			'3006' => '九天云华',
			'3009' => '灵犀箭法',
			'3008' => '暴雨雷鸣箭',
			//九幽
			'4001' => '黑炎',
			'4002' => '雷鸣法咒',
			'4005' => '冰封禁制',
			'4012' => '炎龙破天荒',
		),
		'item_color_name' =>array(
			'1'	=>	'灰色',
			'2' => 	'绿色',
			'3'	=>	'蓝色',
			'4'	=>	'紫色',
			'5'	=>	'真紫',			
			'6'	=>	'橙色',			
			'7'	=>	'真橙',			
		),
		'item_color' =>array(
			'1'	=>	'#cccccc',
			'2' => 	'#00FF00',
			'3'	=>	'#3333FF',
			'4'	=>	'#8a2be2',
			'5'	=>	'#FFCC66',			
		),
		'mentality' =>array(
				'op_type' => array(
					'MentalityMainUpgrade' => '主元神升级',
					'MentalityUpgrade' => '元神升级',
					'MentalityStarUpgrade' => '元神星级升级',
					'MentalityClearUpgradeCD' => '清除升级CD',
					),
				'op_result' => array(
					'Succ' => '成功',
					'Done' => '概率',
					),
				'is_succ' => array(
					'0' => '失败',
					'1' => '成功',
					),
				'is_protect' => array(
					'0' => '未保护',
					'1' => '保护',
					),
		),
		'knapsack' =>array(
				'op_type' => array(
					'Use' => '使用',
					'Discard' => '丢弃',
					'Trade' => '交易',
					'ConsumeItem' => '其它消耗',
					'ConsumeItemByIndex' => '消耗',
					'CertainPut' => '掉落',
					),
				'op_result' => array(
					'Succ' => '成功',
					'Fail' => '失败',
					),
		),
		'equipment' =>array(
				'op_type' => array(
					'Strengthen' => '强化',
					'UnStrengthen'=>'降级',
					'Inlay' => '镶嵌',
					'Uninlay' => '摘除',
					'LiftLevel' => '提阶',
					'Flush' => '洗炼',
					'Decompose' => '分解',
					'Transfer' => '转移',

					),
				'op_result' => array(
					'Succ' => '成功',
					'Fail' => '失败',
					'Canceled' => '取消',
					),
				'flush_type' => array(
					'1'  => '力量',
					'2'  => '奥义',
					'3'  => '智力',
					'4'  => '当前血量',
					'5'  => '最大血量',
					'6'  => '当前法力值',
					'7'  => '最大法力值',
					'8'  => '怒气',
					'9'  => '最大怒气',
					'10' => '物理攻击',
					'11' => '物理防御',
					'12' => '奥义攻击',
					'13' => '奥义防御',
					'14' => '魔法攻击',
					'15' => '魔法防御',
					'16' => '敏捷',
					'17' => '移动速度',
					'18' => '资质',
					'19' => '暴击',
					'20' => '韧性',
					'21' => '命中',
					'22' => '闪避',
					'23' => '抵挡',
					'24' => '反击',
					'25' => '封性',
					),
				'is_protect' => array(
					'0' => '未保护',
					'1' => '保护',
					),
				'color_name' => array(
					'1' => '灰', 		//灰色
					'2' => '绿', 		//绿色
					'3' => '蓝', 		//蓝色
					'4' => '紫',			//紫色
					),
				'color' => array(
					'1' => '#999999', 		//灰色
					'2' => '#00FF00', 		//绿色
					'3' => '#0099FF', 		//蓝色
					'4' => '#6633FF',		//紫色
					),
				'equi_pinzhi_type' => array(	//装备品质类型
					'1' => '普通', 		
					'2' => '优秀', 		
					'3' => '精良', 		
					'4' => '完美',		
					),
				'zuoji_pinzhi_type' => array(	//坐骑品质类型
					'0' => '普通', 		
					'1' => '优秀', 		
					'2' => '精良', 		
					'3' => '完美',		
					'4' => '至尊',		
					),
		),
		'item' =>array(
			'op_type' => array(
					'DanyaoConsume' => '丹药服用',
					'GemstoneCompose' => '宝石合成',
					'ItemCompose' => '物品合成',
					'PotComposeSucc' => '熔炉合成（成功）',
					'PotComposeFail' => '熔炉合成（失败）',
					),
				'op_result' => array(
					'Succ' => '成功',
					'Fail' => '失败',
					),		
		),
		'mount' => array(
			1 => '汗血',
			2 => '赤兔',
			3 => '团团',
			4 => '圆圆',
			5 => '仙羚',
			6 => '幽灵豹',
			7 => '烈魂',
			8 => '追日龙驹',
			9 => '双头狼',
			10=> '印度神象',
			11=> '冰魄',
			12=> '火霞麒麟',
			13=> '凤凰',
			14=> '龙',
			15=> '猎刃豹',			
		),
		'hour' => array(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23),	
		'pet'=>array(
			2 =>'熊猫宝贝',
			3=>'蝴蝶仙子',
			4=>'恐龙',
			5=>'老虎',
			6=>'麒麟',
			7=>'安仔',
			8=>'凤凰',
			9=>'调皮蛋蛋',
		),
);

?>
