<?php

// 日誌解析類型

$Global_Log_Resolve=array(
		'stall' => array(
				'op_type' =>array(
					'Buy' => '購買物品',
					'BuyPet' => '購買寵物',
					'BuyCoin' => '購買銀兩',
					),
				'result_type'=>array(
					'Succ' => '交易成功',
					'Discard_Pet_Fail' => '取出寵物失敗',
				),
		),
		'gold_shop' => array(
				'op_type' => array(
					'BuyShopItem' => '購買物品',
					),
				'result_type' => array(
					'Succ' => '交易成功',
					),
				'price_type' => array(
					'0' => '綁定元寶',
					'2' => '元寶',
					),
		),
		'money_gold' => array(
				'op_type' => array(
					'UseGold' => '使用非綁元寶',
					'UseGoldBind' => '使用綁定元寶',
					'UseAllGold' => '使用所有元寶',
					'Add' => '添加所有元寶',
					'AddGold' => '添加非綁元寶',
					'AddGoldBind' => '添加綁定元寶',
					),
				'op_result' => array(
					'Succ' => '成功',
					),
				'use_for' => array(
					'EquipStrenClearTimer' => '裝備強化清除冷卻時間元寶消耗',
					'OriginClearTimer' => '人物天賦升級清除冷卻時間元寶消耗',
					'MartixOriginClearTimer' => '陣法天賦升級升級清除冷卻時間元寶消耗',
					'MentalityClearTimer' => '元神升級清除冷卻時間元寶消耗',
					'ShopUse' => '商城購買道具消耗',
					'GuildCreate' => '宗族創建元寶消耗',
					'GuildContribute' => '宗族捐獻元寶消耗',
					'RealiveNow' => '角色復活',
					'RealiveHereNow' => '角色原地復活',
					'EquipStrenCertainSucc' => 'VIP裝備強化必定成功',
					'TianshuTaskRefresh' => '天書任務元寶刷新',
					'VipTianshuStarRefresh' => 'VIP天書任務直接刷5星',
					'VipEscortRefresh' => 'VIP運鏢直接刷橙色',
					'EscortRefresh' => '運鏢元寶刷新',
					'EscortRob' => '元寶劫鏢',
					'DongtianTrainCost' => '修鍊花費元寶',
					'DongtianAddTrainGrid' => '修鍊增加格子',
					'TrainBreak' => '修鍊突破',
					'ClearBreakCD' => '清除突破CD',
					'ClearMentalityCD' => '清除元神CD',
					'ClearOriginCD' => '清除天賦CD',
					'DunwuCost' => '頓悟花費元寶',
					'AddXianfaStorage' => '仙法增加格子',
					'OfficerFoster' => '武將洗髓',
					'EscortAccelerate' => '運鏢加速',
					'KnapsackStorageExtendGridNum' => '背包倉庫擴展格子',
					'ClearMartixOriginCD' => '清除陣法天賦CD',
					'QieshiCost' => '元寶切石',
					'ClearQieshiCD' => '清除切石CD',
					'EncourageUse' => '世界BOSS鼓舞',
					'ArenaRefreshOpponent' => '競技場敵人刷新',
					'ArenaChallenge' => '競技場額外挑戰',
					'CleanupAccelerate' => '掛機加速',
					'TreasureChestCost' => '元寶斬仙',
					'TaskReward'=>'任務獎勵',
					'DefinedGift'=>'固定禮包開出',
					'RandGift'=>'隨機禮包開出',
					'GetAccountGold' => '儲值',
					'CreateGuildFailReturn' => '元寶創建宗族失敗返還',
					'CampPositionSalary' => '陣營官職俸祿',
					'MailReceive' => '郵件附件提取',
					'AchiveReward' => '成就獎勵',
					'QieshiReward' => '切石獲得禮金',
					'EquipFlushLock'=>'裝備洗鍊鎖',
					'MysteriousShop'=>'神秘商店',
					'RefrashBoardTask'=>'刷新懸賞任務',
					'GuildOpenBook'=>'宗族密經召喚',
					'VipBuyEnergyToken'=>'vip購買通神令',
					'PersonMapFlushPoint'=>'個人副本刷新',
					'LianTi'=>'煉體',
					'ChestShopBuy'=>'龍脈寶箱',
					'ForbitAreaFlushTower'=>'鎮妖塔刷新',
					'BoardTaskBuyBuff'=>'懸賞固定橙色任務',
					'XRoleArenaCleanAttackCD'=>'競技場清除挑戰CD',
					'MonsterCityReliveNow'=>'怪物攻城原地復活',
					'OfficerChuancheng'=>'家將傳承',
					'LiehunConsume'=>'獵魂',
					'LiehunWagerBiSheng'=>'獵魂必勝',
					),
		),
		'money_coin' => array(
				'op_type' => array(
					'UseCoin' => '使用銀兩',
					'UseCoinTwo' => '使用兩種',
					'UseAllCoin' => '使用所有銀兩',
					'UseAll' => '使用所有',
					'Add' => '添加所有銀兩',
					'AddCoin' => '添加非綁銀兩',
					'AddCoinBind' => '添加綁定銀兩',
					),
				'op_result' => array(
					'Succ' => '成功',
					),
				'coin_add'=>array(
				        'ResFightReward'=>'銀礦戰',
				        'EscortFinish'=>'護送神兵',
				        'TaskReward'=>'懸賞任務',
				        'QieshiReward'=>'招財進寶',
				        'XArenaAttackReward'=>'競技場獎勵',
				        'CoinRuneUse'=>'使用銀兩符',
				        'WorldBossReward'=>'世界BOSS',
				        'QunXianWarCombat'=>'群仙戰',
				        'MonsterCityReward'=>'妖獸來襲',
				        'other'=>'其它',
				),
				'coin_use'=>array(
				        'EquipStrengthen'=>'裝備強化',
				        'WudaoCost'=>'悟道費用',
				        'LiehunConsume'=>'獵魂',
				        'GuildContribute'=>'宗族捐獻',
				        'other'=>'其它',
				),
				'coin_use_type'=>array(
				        'EquipStrengthen'=>'強化統計',
				        'WudaoCost'=>'悟道統計',
				        'LiehunConsume'=>'家將獵魂',
				        'GuildContribute'=>'宗族捐獻',
				),
				'use_for' => array(
					'MentalityUpgrade' => '升級元神消耗',
					'NpcShopUse' => 'NPC商店購買物品',
					'DongtianTrainCost' => '洞天福地銀兩修鍊消耗',
					'DongtianAddTrainGrid' => '洞天福地增加修鍊位元寶消耗',
					'GuildCreate' => '宗族創建消耗',
					'PublicSaleBuy' => '買拍賣品消耗',
					'Other' => '其他（GM命令）',
					'TradeIn' => '交易獲得',
					'WorldBossReward' => '世界BOSS勝利獲得金錢',
					'EquipUnstrengthen' => '裝備降級',
					'CoinRuneUse' => '銀兩符使用',
					'NpcShopSell' => 'npc商店賣',
					'MailReceive' => '郵件附件獲得',
					'NpcShop' => '商店買',
					'TradeOut' => '交易',
					'PK_Cost' => 'PK消費',
					'GuildContribute' => '宗族貢獻',
					'EquipDecompose' => '裝備分解',
					'EquipDressFusion' => '時裝融合',
					'EquipExtendHole' => '裝備打孔',
					'EquipFlush' => '裝備洗鍊',
					'EquipInlay' => '裝備寶石鑲嵌',
					'EquipLiftLevel' => '裝備提階',
					'EquipMountEvolve' => '座騎進階',
					'EquipMountFlush' => '座騎洗髓',
					'EquipRefine' => '裝備精鍊',
					'EquipRepair' => '裝備修理',
					'EquipStrengthen' => '裝備強化',
					'EquipTransfer' => '裝備轉移',
					'EquipUnInlay' => '裝備寶石摘除',
					'EquipUpgrade' => '裝備升級',
					'DongtianTrainCost' => '修鍊費用',
					'WudaoCost' => '悟道費用',
					'SkillUpgrade' => '技能升級費用',
					'MailSend' => '發送郵件固定郵資',
					'PublicSaleChargeCost' => '拍賣管理費',
					'OfficerInnEmploy' => '武將招募費用',
					'GemstoneCompose' => '寶石合成',
					'ItemCompose' => '一般物品合成',
					'PotCompose' => '熔爐合成',
					'TaskReward'=>'任務獎勵',
					'DefinedGift'=>'固定禮包開出',
					'RandGift'=>'隨機禮包開出',
					'NpcShopSell' => '商店賣',
					'CreateGuildFailReturn' => '創建宗族失敗返還銀兩',
					'CampPositionSalary' => '陣營官職俸祿',
					'MailReceive' => '郵件附件提取',
					'EscortFinish' => '運鏢成功',
					'TradeIn' => '交易獲得',
					'MailReceive' => '郵件附件提取',
					'EscortFinish' => '運鏢成功',
					'TradeIn' => '交易獲得',
					'CoinRuneUse' => '使用銀兩符',
					'RandomBossReward' => '雲遊BOSS獎勵',
					'WorldBossReward' => '世界BOSS獎勵',
					'EquipUnstrengthen' => '裝備降級',
					'EscortRobReward' => '劫鏢獎勵',
					'EscortProtectFinish' => '護鏢結束獎勵',
					'PK_Reward' => 'PK獎勵',
					'SellXianfa' => '賣仙法',
					'SellAllXianfa' => '一鍵賣所有仙法',
					'PushMapReward' => '推圖獎勵',
					'QieshiReward' => '切石獲得銀兩',
					'HuanJingReward' => '幻境通關獎勵',
					'PushMapReward' => '推圖獎勵',
					'QieshiReward' => '切石獲得銀兩',
					'HuanJingReward' => '幻境通關獎勵',
					'ArenaRankReward' => '競技場積分獎勵',
					'ExchangeWeiwang' => '陣營威望換取銀兩',
					'LiehunConsume'=>'獵魂',
					),
		),
		'country' =>array(
			'0'	=>	'新手',
			'1'	=>	'魏國',
			'2' => 	'蜀國',
			'3'	=>	'吳國',
		),
		'professional' =>array(
			'0' => 	'新手',
			'1' => 	'勇士',
			'2'	=>	'謀士',
			'3' => 	'羽士',
		),
		'sex' => array(
			'0'=>'女',
			'1'=>'男',
		),
		'sex1'=>array(
			'0'=>'f',
			'1'=>'m',
		),
		'quality' => array(
			'0'=>'無品質',
			'1'=>'普通',
			'2'=>'卓越',
			'3'=>'完美',
		),
		'roleskill_type' =>array(	//技能
			//太玄
			'1001' => '青冥幻斬',
			'1002' => '劍氣縱橫',
			'1004' => '寒冰劍氣',
			'1008' => '一氣化三清',
			//瑤池
			'2001' => '狂斬',
			'2002' => '月影千華',
			'2011' => '破滅輪迴',
			'2009' => '天外飛仙訣',
			//離火
			'3001' => '冰霜箭',
			'3006' => '九天雲華',
			'3009' => '靈犀箭法',
			'3008' => '暴雨雷鳴箭',
			//九幽
			'4001' => '黑炎',
			'4002' => '雷鳴法咒',
			'4005' => '冰封禁制',
			'4012' => '炎龍破天荒',
		),
		'item_color_name' =>array(
			'1'	=>	'灰',
			'2' => 	'綠',
			'3'	=>	'藍',
			'4'	=>	'紫',
			'5'	=>	'橙',			
		),
		'item_color' =>array(
			'1'	=>	'#cccccc',
			'2' => 	'#00FF00',
			'3'	=>	'#3333FF',
			'4'	=>	'#8a2be2',
			'5'	=>	'#FFCC66',			
		),
		'mentality' =>array(
				'op_type' => array(
					'MentalityMainUpgrade' => '主元神升級',
					'MentalityUpgrade' => '元神升級',
					'MentalityStarUpgrade' => '元神星級升級',
					'MentalityClearUpgradeCD' => '清除升級CD',
					),
				'op_result' => array(
					'Succ' => '成功',
					'Done' => '概率',
					),
				'is_succ' => array(
					'0' => '失敗',
					'1' => '成功',
					),
				'is_protect' => array(
					'0' => '未保護',
					'1' => '保護',
					),
		),
		'knapsack' =>array(
				'op_type' => array(
					'Use' => '使用',
					'Discard' => '丟棄',
					'Trade' => '交易',
					'ConsumeItem' => '其它消耗',
					'ConsumeItemByIndex' => '消耗',
					'CertainPut' => '掉落',
					),
				'op_result' => array(
					'Succ' => '成功',
					'Fail' => '失敗',
					),
		),
		'equipment' =>array(
				'op_type' => array(
					'Strengthen' => '強化',
					'UnStrengthen'=>'降級',
					'Inlay' => '鑲嵌',
					'Uninlay' => '摘除',
					'LiftLevel' => '提階',
					'Flush' => '洗鍊',
					'Decompose' => '分解',
					'Transfer' => '轉移',

					),
				'op_result' => array(
					'Succ' => '成功',
					'Fail' => '失敗',
					'Canceled' => '取消',
					),
				'flush_type' => array(
					'1'  => '力量',
					'2'  => '奧義',
					'3'  => '智力',
					'4'  => '當前血量',
					'5'  => '最大血量',
					'6'  => '當前法力值',
					'7'  => '最大法力值',
					'8'  => '怒氣',
					'9'  => '最大怒氣',
					'10' => '物理攻擊',
					'11' => '物理防禦',
					'12' => '奧義攻擊',
					'13' => '奧義防禦',
					'14' => '魔法攻擊',
					'15' => '魔法防禦',
					'16' => '敏捷',
					'17' => '移動速度',
					'18' => '資質',
					'19' => '暴擊',
					'20' => '韌性',
					'21' => '命中',
					'22' => '閃避',
					'23' => '抵擋',
					'24' => '反擊',
					'25' => '封性',
					),
				'is_protect' => array(
					'0' => '未保護',
					'1' => '保護',
					),
				'color_name' => array(
					'1' => '灰', 		//灰色
					'2' => '綠', 		//綠色
					'3' => '藍', 		//藍色
					'4' => '紫',			//紫色
					),
				'color' => array(
					'1' => '#999999', 		//灰色
					'2' => '#00FF00', 		//綠色
					'3' => '#0099FF', 		//藍色
					'4' => '#6633FF',		//紫色
					),
				'equi_pinzhi_type' => array(	//裝備品質類型
					'1' => '普通', 		
					'2' => '優秀', 		
					'3' => '精良', 		
					'4' => '完美',		
					),
				'zuoji_pinzhi_type' => array(	//座騎品質類型
					'0' => '普通', 		
					'1' => '優秀', 		
					'2' => '精良', 		
					'3' => '完美',		
					'4' => '至尊',		
					),
		),
		'item' =>array(
			'op_type' => array(
					'DanyaoConsume' => '丹藥服用',
					'GemstoneCompose' => '寶石合成',
					'ItemCompose' => '物品合成',
					'PotComposeSucc' => '熔爐合成（成功）',
					'PotComposeFail' => '熔爐合成（失敗）',
					),
				'op_result' => array(
					'Succ' => '成功',
					'Fail' => '失敗',
					),		
		),
		'mount' => array(
			1 => '汗血',
			2 => '赤兔',
			3 => '雙頭狼',
			4 => '雪豹（幽靈）',
			5 => '印度神象',
			6 => '烈魂',
			7 => '冰魄',
			8 => '火霞麒麟',
			9 => '鳳凰',
			10=> '龍',
			11=> '情侶熊貓',
			12=> '白澤',
			13=> '霸天虎',			
		),
		'hour' => array(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23),	
);

?>
